# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/bionic64"

  config.vm.box = "system-core/ubuntu"
  config.vm.box_version = "18.04.2"

  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "..", "/usr/share/tigas.io"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
   end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt --yes install apt-transport-https ca-certificates curl software-properties-common
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
     apt-key fingerprint 0EBFCD88
     add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
     apt update
     # apt-get --yes install 'docker-ce=5:18.09.7~3-0~ubuntu-bionic' 'docker-ce-cli=5:18.09.7~3-0~ubuntu-bionic' containerd.io
     apt-get --yes install 'docker-ce=18.06.1~ce~3-0~ubuntu' containerd.io
     apt-mark hold docker-ce
     apt-cache madison docker-ce-cli
     apt-get --yes  install docker-compose
     usermod -aG docker vagrant
     systemctl restart docker
  SHELL
end
